### ISSUE TITLE
 Unable to instantiate model: Model format not supported (no matching implementation found) (type=value_error)

### ISSUE THREAD

**Issue by Lbaiall** [ruddythor/mick.ai#2]
i had try to change all model but it still stuck right this line ！！
Y:\mick.ai\rag>python rag.py
loading model
loading directory Y:\mick.ai\README.txt
Y:\mick.ai\README.txt
instantiated loader
splitting text and embedding using gpt4all embeddings
load_gguf: gguf_init_from_file failed
magic_match: unsupported model architecture:
Traceback (most recent call last):
  File "Y:\mick.ai\rag\rag.py", line 41, in <module>
    vectorstore = Chroma.from_documents(documents=splits, embedding=GPT4AllEmbeddings())
                                                                    ^^^^^^^^^^^^^^^^^^^
  File "pydantic\main.py", line 341, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for GPT4AllEmbeddings
__root__
  Unable to instantiate model: Model format not supported (no matching implementation found) (type=value_error)

**Comment by righteousrenegade** [comment]
oh im just now seeing this! i'll look to see if i can fix this! thanks for the comment!
